// This file is auto-generated by @hey-api/openapi-ts

export const ApiKeyCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        }
    },
    type: 'object',
    required: [
        'name'
    ],
    title: 'ApiKeyCreate'
} as const;

export const ApiKeyCreatePublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        key: {
            type: 'string',
            title: 'Key'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'name',
        'key',
        'created_at'
    ],
    title: 'ApiKeyCreatePublic'
} as const;

export const ApiKeyPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        key_prefix: {
            type: 'string',
            title: 'Key Prefix'
        },
        last_used_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Used At'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'key_prefix',
        'last_used_at',
        'created_at'
    ],
    title: 'ApiKeyPublic'
} as const;

export const ApiKeysPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/ApiKeyPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'ApiKeysPublic'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login-login_access_token'
} as const;

export const FCMTokenUpdateSchema = {
    properties: {
        fcm_token: {
            type: 'string',
            maxLength: 255,
            title: 'Fcm Token'
        }
    },
    type: 'object',
    required: [
        'fcm_token'
    ],
    title: 'FCMTokenUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const PlanUpgradeSchema = {
    properties: {
        plan_id: {
            type: 'string',
            format: 'uuid',
            title: 'Plan Id'
        }
    },
    type: 'object',
    required: [
        'plan_id'
    ],
    title: 'PlanUpgrade'
} as const;

export const PlanUpgradePublicSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        },
        data: {
            additionalProperties: {
                type: 'string'
            },
            type: 'object',
            title: 'Data'
        }
    },
    type: 'object',
    required: [
        'message',
        'data'
    ],
    title: 'PlanUpgradePublic'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        full_name: {
            type: 'string',
            title: 'Full Name'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: [
        'email',
        'password',
        'full_name'
    ],
    title: 'PrivateUserCreate'
} as const;

export const SMSDeviceCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        phone_number: {
            type: 'string',
            maxLength: 20,
            title: 'Phone Number'
        }
    },
    type: 'object',
    required: [
        'name',
        'phone_number'
    ],
    title: 'SMSDeviceCreate'
} as const;

export const SMSDeviceCreatePublicSchema = {
    properties: {
        device_id: {
            type: 'string',
            format: 'uuid',
            title: 'Device Id'
        },
        api_key: {
            type: 'string',
            title: 'Api Key'
        }
    },
    type: 'object',
    required: [
        'device_id',
        'api_key'
    ],
    title: 'SMSDeviceCreatePublic'
} as const;

export const SMSDevicePublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        phone_number: {
            type: 'string',
            maxLength: 20,
            title: 'Phone Number'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'name',
        'phone_number',
        'id',
        'user_id',
        'created_at',
        'updated_at'
    ],
    title: 'SMSDevicePublic'
} as const;

export const SMSDeviceUpdateSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        }
    },
    type: 'object',
    title: 'SMSDeviceUpdate'
} as const;

export const SMSDevicesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/SMSDevicePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'SMSDevicesPublic'
} as const;

export const SMSIncomingSchema = {
    properties: {
        from_number: {
            type: 'string',
            maxLength: 20,
            title: 'From Number'
        },
        body: {
            type: 'string',
            maxLength: 1600,
            title: 'Body'
        },
        timestamp: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Timestamp'
        }
    },
    type: 'object',
    required: [
        'from_number',
        'body'
    ],
    title: 'SMSIncoming'
} as const;

export const SMSMessageCreateSchema = {
    properties: {
        recipients: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Recipients'
        },
        body: {
            type: 'string',
            maxLength: 1600,
            title: 'Body'
        },
        device_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Id'
        }
    },
    type: 'object',
    required: [
        'recipients',
        'body'
    ],
    title: 'SMSMessageCreate'
} as const;

export const SMSMessagePublicSchema = {
    properties: {
        to: {
            type: 'string',
            maxLength: 20,
            title: 'To'
        },
        from_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 20
                },
                {
                    type: 'null'
                }
            ],
            title: 'From Number'
        },
        body: {
            type: 'string',
            maxLength: 1600,
            title: 'Body'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status',
            default: 'pending'
        },
        message_type: {
            type: 'string',
            maxLength: 50,
            title: 'Message Type',
            default: 'outgoing'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        batch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Batch Id'
        },
        device_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Device Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        webhook_sent: {
            type: 'boolean',
            title: 'Webhook Sent'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        sent_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sent At'
        },
        delivered_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Delivered At'
        }
    },
    type: 'object',
    required: [
        'to',
        'body',
        'id',
        'batch_id',
        'device_id',
        'user_id',
        'webhook_sent',
        'error_message',
        'created_at',
        'updated_at',
        'sent_at',
        'delivered_at'
    ],
    title: 'SMSMessagePublic'
} as const;

export const SMSMessageSendPublicSchema = {
    properties: {
        batch_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Batch Id'
        },
        message_ids: {
            items: {
                type: 'string',
                format: 'uuid'
            },
            type: 'array',
            title: 'Message Ids'
        },
        recipients_count: {
            type: 'integer',
            title: 'Recipients Count'
        },
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: [
        'batch_id',
        'message_ids',
        'recipients_count',
        'status'
    ],
    title: 'SMSMessageSendPublic'
} as const;

export const SMSMessagesPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/SMSMessagePublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'SMSMessagesPublic'
} as const;

export const SMSReportSchema = {
    properties: {
        message_id: {
            type: 'string',
            format: 'uuid',
            title: 'Message Id'
        },
        status: {
            type: 'string',
            maxLength: 50,
            title: 'Status'
        },
        error_message: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Error Message'
        }
    },
    type: 'object',
    required: [
        'message_id',
        'status'
    ],
    title: 'SMSReport'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email_verified: {
            type: 'boolean',
            title: 'Email Verified',
            default: false
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserPlanPublicSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        max_sms_per_month: {
            type: 'integer',
            title: 'Max Sms Per Month',
            default: 0
        },
        max_devices: {
            type: 'integer',
            title: 'Max Devices',
            default: 0
        },
        price: {
            type: 'number',
            title: 'Price',
            default: 0
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'name',
        'id',
        'created_at',
        'updated_at'
    ],
    title: 'UserPlanPublic'
} as const;

export const UserPlansPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPlanPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UserPlansPublic'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email_verified: {
            type: 'boolean',
            title: 'Email Verified',
            default: false
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserQuotaPublicSchema = {
    properties: {
        plan: {
            type: 'string',
            title: 'Plan'
        },
        sms_sent_this_month: {
            type: 'integer',
            title: 'Sms Sent This Month'
        },
        max_sms_per_month: {
            type: 'integer',
            title: 'Max Sms Per Month'
        },
        devices_registered: {
            type: 'integer',
            title: 'Devices Registered'
        },
        max_devices: {
            type: 'integer',
            title: 'Max Devices'
        },
        reset_date: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Reset Date'
        }
    },
    type: 'object',
    required: [
        'plan',
        'sms_sent_this_month',
        'max_sms_per_month',
        'devices_registered',
        'max_devices',
        'reset_date'
    ],
    title: 'UserQuotaPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 128,
            minLength: 8,
            title: 'Password'
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email_verified: {
            type: 'boolean',
            title: 'Email Verified',
            default: false
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 128,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        full_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Full Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const WebhookConfigCreateSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 500,
            title: 'Url'
        },
        secret_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Key'
        },
        events: {
            type: 'string',
            maxLength: 500,
            title: 'Events',
            default: '["sms_received"]'
        },
        active: {
            type: 'boolean',
            title: 'Active',
            default: true
        }
    },
    type: 'object',
    required: [
        'url'
    ],
    title: 'WebhookConfigCreate'
} as const;

export const WebhookConfigPublicSchema = {
    properties: {
        url: {
            type: 'string',
            maxLength: 500,
            title: 'Url'
        },
        secret_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Key'
        },
        events: {
            type: 'string',
            maxLength: 500,
            title: 'Events',
            default: '["sms_received"]'
        },
        active: {
            type: 'boolean',
            title: 'Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'url',
        'id',
        'user_id',
        'created_at',
        'updated_at'
    ],
    title: 'WebhookConfigPublic'
} as const;

export const WebhookConfigUpdateSchema = {
    properties: {
        url: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Url'
        },
        secret_key: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Secret Key'
        },
        events: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 500
                },
                {
                    type: 'null'
                }
            ],
            title: 'Events'
        },
        active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Active'
        }
    },
    type: 'object',
    title: 'WebhookConfigUpdate'
} as const;

export const WebhookConfigsPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/WebhookConfigPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'WebhookConfigsPublic'
} as const;
