// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { LoginLoginAccessTokenData, LoginLoginAccessTokenResponse, LoginTestTokenResponse, LoginRecoverPasswordData, LoginRecoverPasswordResponse, LoginResetPasswordData, LoginResetPasswordResponse, LoginRecoverPasswordHtmlContentData, LoginRecoverPasswordHtmlContentResponse, PlansListPlansResponse, PlansGetQuotaResponse, PlansUpgradePlanData, PlansUpgradePlanResponse, SmsSendSmsData, SmsSendSmsResponse, SmsListMessagesData, SmsListMessagesResponse, SmsGetMessageData, SmsGetMessageResponse, SmsListIncomingMessagesData, SmsListIncomingMessagesResponse, SmsReportIncomingSmsData, SmsReportIncomingSmsResponse, SmsCreateDeviceData, SmsCreateDeviceResponse, SmsListDevicesData, SmsListDevicesResponse, SmsGetDeviceData, SmsGetDeviceResponse, SmsUpdateDeviceData, SmsUpdateDeviceResponse, SmsDeleteDeviceData, SmsDeleteDeviceResponse, SmsReportSmsStatusData, SmsReportSmsStatusResponse, SmsUpdateFcmTokenData, SmsUpdateFcmTokenResponse, SmsDeviceHeartbeatResponse, UsersReadUsersData, UsersReadUsersResponse, UsersCreateUserData, UsersCreateUserResponse, UsersReadUserMeResponse, UsersDeleteUserMeResponse, UsersUpdateUserMeData, UsersUpdateUserMeResponse, UsersUpdatePasswordMeData, UsersUpdatePasswordMeResponse, UsersRegisterUserData, UsersRegisterUserResponse, UsersReadUserByIdData, UsersReadUserByIdResponse, UsersUpdateUserData, UsersUpdateUserResponse, UsersDeleteUserData, UsersDeleteUserResponse, UtilsHealthCheckResponse, WebhooksCreateWebhookData, WebhooksCreateWebhookResponse, WebhooksListWebhooksData, WebhooksListWebhooksResponse, WebhooksGetWebhookData, WebhooksGetWebhookResponse, WebhooksUpdateWebhookData, WebhooksUpdateWebhookResponse, WebhooksDeleteWebhookData, WebhooksDeleteWebhookResponse } from './types.gen';

export class LoginService {
    /**
     * Login Access Token
     * OAuth2 compatible token login, get an access token for future requests
     * @param data The data for the request.
     * @param data.formData
     * @returns Token Successful Response
     * @throws ApiError
     */
    public static loginAccessToken(data: LoginLoginAccessTokenData): CancelablePromise<LoginLoginAccessTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/access-token',
            formData: data.formData,
            mediaType: 'application/x-www-form-urlencoded',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Test Token
     * Test access token
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static testToken(): CancelablePromise<LoginTestTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/login/test-token'
        });
    }
    
    /**
     * Recover Password
     * Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static recoverPassword(data: LoginRecoverPasswordData): CancelablePromise<LoginRecoverPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Reset Password
     * Reset password
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static resetPassword(data: LoginResetPasswordData): CancelablePromise<LoginResetPasswordResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/reset-password/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Recover Password Html Content
     * HTML Content for Password Recovery
     * @param data The data for the request.
     * @param data.email
     * @returns string Successful Response
     * @throws ApiError
     */
    public static recoverPasswordHtmlContent(data: LoginRecoverPasswordHtmlContentData): CancelablePromise<LoginRecoverPasswordHtmlContentResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/password-recovery-html-content/{email}',
            path: {
                email: data.email
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class PlansService {
    /**
     * List Plans
     * List available plans
     * @returns UserPlansPublic Successful Response
     * @throws ApiError
     */
    public static listPlans(): CancelablePromise<PlansListPlansResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/plans/list'
        });
    }
    
    /**
     * Get Quota
     * Get user quota information
     * @returns UserQuotaPublic Successful Response
     * @throws ApiError
     */
    public static getQuota(): CancelablePromise<PlansGetQuotaResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/plans/quota'
        });
    }
    
    /**
     * Upgrade Plan
     * Change user plan (requires superuser or payment integration)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns PlanUpgradePublic Successful Response
     * @throws ApiError
     */
    public static upgradePlan(data: PlansUpgradePlanData): CancelablePromise<PlansUpgradePlanResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/plans/upgrade',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class SmsService {
    /**
     * Send Sms
     * Send SMS (Single or Bulk)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SMSMessageSendPublic Successful Response
     * @throws ApiError
     */
    public static sendSms(data: SmsSendSmsData): CancelablePromise<SmsSendSmsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/send',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Messages
     * List messages
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @param data.messageType
     * @returns SMSMessagesPublic Successful Response
     * @throws ApiError
     */
    public static listMessages(data: SmsListMessagesData = {}): CancelablePromise<SmsListMessagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sms/messages',
            query: {
                skip: data.skip,
                limit: data.limit,
                message_type: data.messageType
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Message
     * Get specific message
     * @param data The data for the request.
     * @param data.messageId
     * @returns SMSMessagePublic Successful Response
     * @throws ApiError
     */
    public static getMessage(data: SmsGetMessageData): CancelablePromise<SmsGetMessageResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sms/messages/{message_id}',
            path: {
                message_id: data.messageId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Incoming Messages
     * List incoming SMS
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns SMSMessagesPublic Successful Response
     * @throws ApiError
     */
    public static listIncomingMessages(data: SmsListIncomingMessagesData = {}): CancelablePromise<SmsListIncomingMessagesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sms/incoming',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Report Incoming Sms
     * Callback for Android device to report received SMS
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static reportIncomingSms(data: SmsReportIncomingSmsData): CancelablePromise<SmsReportIncomingSmsResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/incoming',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create Device
     * Register new device
     * @param data The data for the request.
     * @param data.requestBody
     * @returns SMSDeviceCreatePublic Successful Response
     * @throws ApiError
     */
    public static createDevice(data: SmsCreateDeviceData): CancelablePromise<SmsCreateDeviceResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/devices',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Devices
     * Get devices
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns SMSDevicesPublic Successful Response
     * @throws ApiError
     */
    public static listDevices(data: SmsListDevicesData = {}): CancelablePromise<SmsListDevicesResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sms/devices',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Device
     * Get device
     * @param data The data for the request.
     * @param data.deviceId
     * @returns SMSDevicePublic Successful Response
     * @throws ApiError
     */
    public static getDevice(data: SmsGetDeviceData): CancelablePromise<SmsGetDeviceResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/sms/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Device
     * Update device
     * @param data The data for the request.
     * @param data.deviceId
     * @param data.requestBody
     * @returns SMSDevicePublic Successful Response
     * @throws ApiError
     */
    public static updateDevice(data: SmsUpdateDeviceData): CancelablePromise<SmsUpdateDeviceResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/sms/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Device
     * Delete device
     * @param data The data for the request.
     * @param data.deviceId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteDevice(data: SmsDeleteDeviceData): CancelablePromise<SmsDeleteDeviceResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/sms/devices/{device_id}',
            path: {
                device_id: data.deviceId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Report Sms Status
     * Callback for Android device to report SMS sending status (ACK)
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static reportSmsStatus(data: SmsReportSmsStatusData): CancelablePromise<SmsReportSmsStatusResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/report',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Fcm Token
     * Update device FCM token using API Key
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updateFcmToken(data: SmsUpdateFcmTokenData): CancelablePromise<SmsUpdateFcmTokenResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/fcm-token',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Device Heartbeat
     * Update device last heartbeat and status
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deviceHeartbeat(): CancelablePromise<SmsDeviceHeartbeatResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/sms/heartbeat'
        });
    }
}

export class UsersService {
    /**
     * Read Users
     * Retrieve users.
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns UsersPublic Successful Response
     * @throws ApiError
     */
    public static readUsers(data: UsersReadUsersData = {}): CancelablePromise<UsersReadUsersResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Create User
     * Create new user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static createUser(data: UsersCreateUserData): CancelablePromise<UsersCreateUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User Me
     * Get current user.
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserMe(): CancelablePromise<UsersReadUserMeResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Delete User Me
     * Delete own user.
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUserMe(): CancelablePromise<UsersDeleteUserMeResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/me'
        });
    }
    
    /**
     * Update User Me
     * Update own user.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUserMe(data: UsersUpdateUserMeData): CancelablePromise<UsersUpdateUserMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Password Me
     * Update own password.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static updatePasswordMe(data: UsersUpdatePasswordMeData): CancelablePromise<UsersUpdatePasswordMeResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/me/password',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Register User
     * Create new user without the need to be logged in.
     * @param data The data for the request.
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static registerUser(data: UsersRegisterUserData): CancelablePromise<UsersRegisterUserResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/users/signup',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Read User By Id
     * Get a specific user by id.
     * @param data The data for the request.
     * @param data.userId
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static readUserById(data: UsersReadUserByIdData): CancelablePromise<UsersReadUserByIdResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update User
     * Update a user.
     * @param data The data for the request.
     * @param data.userId
     * @param data.requestBody
     * @returns UserPublic Successful Response
     * @throws ApiError
     */
    public static updateUser(data: UsersUpdateUserData): CancelablePromise<UsersUpdateUserResponse> {
        return __request(OpenAPI, {
            method: 'PATCH',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete User
     * Delete a user.
     * @param data The data for the request.
     * @param data.userId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteUser(data: UsersDeleteUserData): CancelablePromise<UsersDeleteUserResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/users/{user_id}',
            path: {
                user_id: data.userId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}

export class UtilsService {
    /**
     * Health Check
     * @returns boolean Successful Response
     * @throws ApiError
     */
    public static healthCheck(): CancelablePromise<UtilsHealthCheckResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/utils/health-check/'
        });
    }
}

export class WebhooksService {
    /**
     * Create Webhook
     * Create/configure webhook
     * @param data The data for the request.
     * @param data.requestBody
     * @returns WebhookConfigPublic Successful Response
     * @throws ApiError
     */
    public static createWebhook(data: WebhooksCreateWebhookData): CancelablePromise<WebhooksCreateWebhookResponse> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/v1/webhooks',
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * List Webhooks
     * List configured webhooks
     * @param data The data for the request.
     * @param data.skip
     * @param data.limit
     * @returns WebhookConfigsPublic Successful Response
     * @throws ApiError
     */
    public static listWebhooks(data: WebhooksListWebhooksData = {}): CancelablePromise<WebhooksListWebhooksResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/webhooks',
            query: {
                skip: data.skip,
                limit: data.limit
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Get Webhook
     * Get specific webhook
     * @param data The data for the request.
     * @param data.webhookId
     * @returns WebhookConfigPublic Successful Response
     * @throws ApiError
     */
    public static getWebhook(data: WebhooksGetWebhookData): CancelablePromise<WebhooksGetWebhookResponse> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/v1/webhooks/{webhook_id}',
            path: {
                webhook_id: data.webhookId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Update Webhook
     * Update webhook
     * @param data The data for the request.
     * @param data.webhookId
     * @param data.requestBody
     * @returns WebhookConfigPublic Successful Response
     * @throws ApiError
     */
    public static updateWebhook(data: WebhooksUpdateWebhookData): CancelablePromise<WebhooksUpdateWebhookResponse> {
        return __request(OpenAPI, {
            method: 'PUT',
            url: '/api/v1/webhooks/{webhook_id}',
            path: {
                webhook_id: data.webhookId
            },
            body: data.requestBody,
            mediaType: 'application/json',
            errors: {
                422: 'Validation Error'
            }
        });
    }
    
    /**
     * Delete Webhook
     * Delete webhook
     * @param data The data for the request.
     * @param data.webhookId
     * @returns Message Successful Response
     * @throws ApiError
     */
    public static deleteWebhook(data: WebhooksDeleteWebhookData): CancelablePromise<WebhooksDeleteWebhookResponse> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/v1/webhooks/{webhook_id}',
            path: {
                webhook_id: data.webhookId
            },
            errors: {
                422: 'Validation Error'
            }
        });
    }
}