// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * ApiKeyCreate
 */
export type ApiKeyCreate = {
    /**
     * Name
     */
    name: string;
};

/**
 * ApiKeyCreatePublic
 */
export type ApiKeyCreatePublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Key
     */
    key: string;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ApiKeyPublic
 */
export type ApiKeyPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Key Prefix
     */
    key_prefix: string;
    /**
     * Last Used At
     */
    last_used_at: string | null;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * ApiKeysPublic
 */
export type ApiKeysPublic = {
    /**
     * Data
     */
    data: Array<ApiKeyPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * Body_login-login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * FCMTokenUpdate
 */
export type FcmTokenUpdate = {
    /**
     * Fcm Token
     */
    fcm_token: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PlanUpgrade
 */
export type PlanUpgrade = {
    /**
     * Plan Id
     */
    plan_id: string;
};

/**
 * PlanUpgradePublic
 */
export type PlanUpgradePublic = {
    /**
     * Message
     */
    message: string;
    /**
     * Data
     */
    data: {
        [key: string]: string;
    };
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name: string;
    /**
     * Is Verified
     */
    is_verified?: boolean;
};

/**
 * SMSDeviceCreate
 */
export type SmsDeviceCreate = {
    /**
     * Name
     */
    name: string;
    /**
     * Phone Number
     */
    phone_number: string;
};

/**
 * SMSDeviceCreatePublic
 */
export type SmsDeviceCreatePublic = {
    /**
     * Device Id
     */
    device_id: string;
    /**
     * Api Key
     */
    api_key: string;
};

/**
 * SMSDevicePublic
 */
export type SmsDevicePublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Phone Number
     */
    phone_number: string;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * SMSDeviceUpdate
 */
export type SmsDeviceUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Phone Number
     */
    phone_number?: string | null;
};

/**
 * SMSDevicesPublic
 */
export type SmsDevicesPublic = {
    /**
     * Data
     */
    data: Array<SmsDevicePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SMSIncoming
 */
export type SmsIncoming = {
    /**
     * From Number
     */
    from_number: string;
    /**
     * Body
     */
    body: string;
    /**
     * Timestamp
     */
    timestamp?: string | null;
};

/**
 * SMSMessageCreate
 */
export type SmsMessageCreate = {
    /**
     * Recipients
     */
    recipients: Array<string>;
    /**
     * Body
     */
    body: string;
    /**
     * Device Id
     */
    device_id?: string | null;
};

/**
 * SMSMessagePublic
 */
export type SmsMessagePublic = {
    /**
     * To
     */
    to: string;
    /**
     * From Number
     */
    from_number?: string | null;
    /**
     * Body
     */
    body: string;
    /**
     * Status
     */
    status?: string;
    /**
     * Message Type
     */
    message_type?: string;
    /**
     * Id
     */
    id: string;
    /**
     * Batch Id
     */
    batch_id: string | null;
    /**
     * Device Id
     */
    device_id: string | null;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Webhook Sent
     */
    webhook_sent: boolean;
    /**
     * Error Message
     */
    error_message: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Sent At
     */
    sent_at: string | null;
    /**
     * Delivered At
     */
    delivered_at: string | null;
};

/**
 * SMSMessageSendPublic
 */
export type SmsMessageSendPublic = {
    /**
     * Batch Id
     */
    batch_id: string | null;
    /**
     * Message Ids
     */
    message_ids: Array<string>;
    /**
     * Recipients Count
     */
    recipients_count: number;
    /**
     * Status
     */
    status: string;
};

/**
 * SMSMessagesPublic
 */
export type SmsMessagesPublic = {
    /**
     * Data
     */
    data: Array<SmsMessagePublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * SMSReport
 */
export type SmsReport = {
    /**
     * Message Id
     */
    message_id: string;
    /**
     * Status
     */
    status: string;
    /**
     * Error Message
     */
    error_message?: string | null;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Password
     */
    password: string;
};

/**
 * UserPlanPublic
 */
export type UserPlanPublic = {
    /**
     * Name
     */
    name: string;
    /**
     * Max Sms Per Month
     */
    max_sms_per_month?: number;
    /**
     * Max Devices
     */
    max_devices?: number;
    /**
     * Price
     */
    price?: number;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * UserPlansPublic
 */
export type UserPlansPublic = {
    /**
     * Data
     */
    data: Array<UserPlanPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Id
     */
    id: string;
};

/**
 * UserQuotaPublic
 */
export type UserQuotaPublic = {
    /**
     * Plan
     */
    plan: string;
    /**
     * Sms Sent This Month
     */
    sms_sent_this_month: number;
    /**
     * Max Sms Per Month
     */
    max_sms_per_month: number;
    /**
     * Devices Registered
     */
    devices_registered: number;
    /**
     * Max Devices
     */
    max_devices: number;
    /**
     * Reset Date
     */
    reset_date: string | null;
};

/**
 * UserRegister
 */
export type UserRegister = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Full Name
     */
    full_name?: string | null;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email Verified
     */
    email_verified?: boolean;
    /**
     * Password
     */
    password?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * Full Name
     */
    full_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * WebhookConfigCreate
 */
export type WebhookConfigCreate = {
    /**
     * Url
     */
    url: string;
    /**
     * Secret Key
     */
    secret_key?: string | null;
    /**
     * Events
     */
    events?: string;
    /**
     * Active
     */
    active?: boolean;
};

/**
 * WebhookConfigPublic
 */
export type WebhookConfigPublic = {
    /**
     * Url
     */
    url: string;
    /**
     * Secret Key
     */
    secret_key?: string | null;
    /**
     * Events
     */
    events?: string;
    /**
     * Active
     */
    active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * User Id
     */
    user_id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * WebhookConfigUpdate
 */
export type WebhookConfigUpdate = {
    /**
     * Url
     */
    url?: string | null;
    /**
     * Secret Key
     */
    secret_key?: string | null;
    /**
     * Events
     */
    events?: string | null;
    /**
     * Active
     */
    active?: boolean | null;
};

/**
 * WebhookConfigsPublic
 */
export type WebhookConfigsPublic = {
    /**
     * Data
     */
    data: Array<WebhookConfigPublic>;
    /**
     * Count
     */
    count: number;
};

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersRegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type UsersRegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersRegisterUserError = UsersRegisterUserErrors[keyof UsersRegisterUserErrors];

export type UsersRegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersRegisterUserResponse = UsersRegisterUserResponses[keyof UsersRegisterUserResponses];

export type UsersVerifyEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Token
         */
        token: string;
    };
    url: '/api/v1/users/verify-email';
};

export type UsersVerifyEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersVerifyEmailError = UsersVerifyEmailErrors[keyof UsersVerifyEmailErrors];

export type UsersVerifyEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersVerifyEmailResponse = UsersVerifyEmailResponses[keyof UsersVerifyEmailResponses];

export type UsersResendVerificationEmailData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Email
         */
        email: string;
    };
    url: '/api/v1/users/resend-verification';
};

export type UsersResendVerificationEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersResendVerificationEmailError = UsersResendVerificationEmailErrors[keyof UsersResendVerificationEmailErrors];

export type UsersResendVerificationEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersResendVerificationEmailResponse = UsersResendVerificationEmailResponses[keyof UsersResendVerificationEmailResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdate;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type UtilsHealthCheckData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/utils/health-check/';
};

export type UtilsHealthCheckResponses = {
    /**
     * Response Utils-Health Check
     *
     * Successful Response
     */
    200: boolean;
};

export type UtilsHealthCheckResponse = UtilsHealthCheckResponses[keyof UtilsHealthCheckResponses];

export type SmsSendSmsData = {
    body: SmsMessageCreate;
    path?: never;
    query?: never;
    url: '/api/v1/sms/send';
};

export type SmsSendSmsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsSendSmsError = SmsSendSmsErrors[keyof SmsSendSmsErrors];

export type SmsSendSmsResponses = {
    /**
     * Successful Response
     */
    201: SmsMessageSendPublic;
};

export type SmsSendSmsResponse = SmsSendSmsResponses[keyof SmsSendSmsResponses];

export type SmsListMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Message Type
         */
        message_type?: string | null;
    };
    url: '/api/v1/sms/messages';
};

export type SmsListMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsListMessagesError = SmsListMessagesErrors[keyof SmsListMessagesErrors];

export type SmsListMessagesResponses = {
    /**
     * Successful Response
     */
    200: SmsMessagesPublic;
};

export type SmsListMessagesResponse = SmsListMessagesResponses[keyof SmsListMessagesResponses];

export type SmsGetMessageData = {
    body?: never;
    path: {
        /**
         * Message Id
         */
        message_id: string;
    };
    query?: never;
    url: '/api/v1/sms/messages/{message_id}';
};

export type SmsGetMessageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsGetMessageError = SmsGetMessageErrors[keyof SmsGetMessageErrors];

export type SmsGetMessageResponses = {
    /**
     * Successful Response
     */
    200: SmsMessagePublic;
};

export type SmsGetMessageResponse = SmsGetMessageResponses[keyof SmsGetMessageResponses];

export type SmsListIncomingMessagesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/sms/incoming';
};

export type SmsListIncomingMessagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsListIncomingMessagesError = SmsListIncomingMessagesErrors[keyof SmsListIncomingMessagesErrors];

export type SmsListIncomingMessagesResponses = {
    /**
     * Successful Response
     */
    200: SmsMessagesPublic;
};

export type SmsListIncomingMessagesResponse = SmsListIncomingMessagesResponses[keyof SmsListIncomingMessagesResponses];

export type SmsReportIncomingSmsData = {
    body: SmsIncoming;
    path?: never;
    query?: never;
    url: '/api/v1/sms/incoming';
};

export type SmsReportIncomingSmsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsReportIncomingSmsError = SmsReportIncomingSmsErrors[keyof SmsReportIncomingSmsErrors];

export type SmsReportIncomingSmsResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SmsReportIncomingSmsResponse = SmsReportIncomingSmsResponses[keyof SmsReportIncomingSmsResponses];

export type SmsListDevicesData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/sms/devices';
};

export type SmsListDevicesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsListDevicesError = SmsListDevicesErrors[keyof SmsListDevicesErrors];

export type SmsListDevicesResponses = {
    /**
     * Successful Response
     */
    200: SmsDevicesPublic;
};

export type SmsListDevicesResponse = SmsListDevicesResponses[keyof SmsListDevicesResponses];

export type SmsCreateDeviceData = {
    body: SmsDeviceCreate;
    path?: never;
    query?: never;
    url: '/api/v1/sms/devices';
};

export type SmsCreateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsCreateDeviceError = SmsCreateDeviceErrors[keyof SmsCreateDeviceErrors];

export type SmsCreateDeviceResponses = {
    /**
     * Successful Response
     */
    201: SmsDeviceCreatePublic;
};

export type SmsCreateDeviceResponse = SmsCreateDeviceResponses[keyof SmsCreateDeviceResponses];

export type SmsDeleteDeviceData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/sms/devices/{device_id}';
};

export type SmsDeleteDeviceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsDeleteDeviceError = SmsDeleteDeviceErrors[keyof SmsDeleteDeviceErrors];

export type SmsDeleteDeviceResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SmsDeleteDeviceResponse = SmsDeleteDeviceResponses[keyof SmsDeleteDeviceResponses];

export type SmsGetDeviceData = {
    body?: never;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/sms/devices/{device_id}';
};

export type SmsGetDeviceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsGetDeviceError = SmsGetDeviceErrors[keyof SmsGetDeviceErrors];

export type SmsGetDeviceResponses = {
    /**
     * Successful Response
     */
    200: SmsDevicePublic;
};

export type SmsGetDeviceResponse = SmsGetDeviceResponses[keyof SmsGetDeviceResponses];

export type SmsUpdateDeviceData = {
    body: SmsDeviceUpdate;
    path: {
        /**
         * Device Id
         */
        device_id: string;
    };
    query?: never;
    url: '/api/v1/sms/devices/{device_id}';
};

export type SmsUpdateDeviceErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsUpdateDeviceError = SmsUpdateDeviceErrors[keyof SmsUpdateDeviceErrors];

export type SmsUpdateDeviceResponses = {
    /**
     * Successful Response
     */
    200: SmsDevicePublic;
};

export type SmsUpdateDeviceResponse = SmsUpdateDeviceResponses[keyof SmsUpdateDeviceResponses];

export type SmsReportSmsStatusData = {
    body: SmsReport;
    path?: never;
    query?: never;
    url: '/api/v1/sms/report';
};

export type SmsReportSmsStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsReportSmsStatusError = SmsReportSmsStatusErrors[keyof SmsReportSmsStatusErrors];

export type SmsReportSmsStatusResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SmsReportSmsStatusResponse = SmsReportSmsStatusResponses[keyof SmsReportSmsStatusResponses];

export type SmsUpdateFcmTokenData = {
    body: FcmTokenUpdate;
    path?: never;
    query?: never;
    url: '/api/v1/sms/fcm-token';
};

export type SmsUpdateFcmTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type SmsUpdateFcmTokenError = SmsUpdateFcmTokenErrors[keyof SmsUpdateFcmTokenErrors];

export type SmsUpdateFcmTokenResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type SmsUpdateFcmTokenResponse = SmsUpdateFcmTokenResponses[keyof SmsUpdateFcmTokenResponses];

export type PlansListPlansData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/list';
};

export type PlansListPlansResponses = {
    /**
     * Successful Response
     */
    200: UserPlansPublic;
};

export type PlansListPlansResponse = PlansListPlansResponses[keyof PlansListPlansResponses];

export type PlansGetQuotaData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/plans/quota';
};

export type PlansGetQuotaResponses = {
    /**
     * Successful Response
     */
    200: UserQuotaPublic;
};

export type PlansGetQuotaResponse = PlansGetQuotaResponses[keyof PlansGetQuotaResponses];

export type PlansUpgradePlanData = {
    body: PlanUpgrade;
    path?: never;
    query?: never;
    url: '/api/v1/plans/upgrade';
};

export type PlansUpgradePlanErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PlansUpgradePlanError = PlansUpgradePlanErrors[keyof PlansUpgradePlanErrors];

export type PlansUpgradePlanResponses = {
    /**
     * Successful Response
     */
    200: PlanUpgradePublic;
};

export type PlansUpgradePlanResponse = PlansUpgradePlanResponses[keyof PlansUpgradePlanResponses];

export type WebhooksListWebhooksData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/webhooks';
};

export type WebhooksListWebhooksErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksListWebhooksError = WebhooksListWebhooksErrors[keyof WebhooksListWebhooksErrors];

export type WebhooksListWebhooksResponses = {
    /**
     * Successful Response
     */
    200: WebhookConfigsPublic;
};

export type WebhooksListWebhooksResponse = WebhooksListWebhooksResponses[keyof WebhooksListWebhooksResponses];

export type WebhooksCreateWebhookData = {
    body: WebhookConfigCreate;
    path?: never;
    query?: never;
    url: '/api/v1/webhooks';
};

export type WebhooksCreateWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksCreateWebhookError = WebhooksCreateWebhookErrors[keyof WebhooksCreateWebhookErrors];

export type WebhooksCreateWebhookResponses = {
    /**
     * Successful Response
     */
    201: WebhookConfigPublic;
};

export type WebhooksCreateWebhookResponse = WebhooksCreateWebhookResponses[keyof WebhooksCreateWebhookResponses];

export type WebhooksDeleteWebhookData = {
    body?: never;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{webhook_id}';
};

export type WebhooksDeleteWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksDeleteWebhookError = WebhooksDeleteWebhookErrors[keyof WebhooksDeleteWebhookErrors];

export type WebhooksDeleteWebhookResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type WebhooksDeleteWebhookResponse = WebhooksDeleteWebhookResponses[keyof WebhooksDeleteWebhookResponses];

export type WebhooksGetWebhookData = {
    body?: never;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{webhook_id}';
};

export type WebhooksGetWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksGetWebhookError = WebhooksGetWebhookErrors[keyof WebhooksGetWebhookErrors];

export type WebhooksGetWebhookResponses = {
    /**
     * Successful Response
     */
    200: WebhookConfigPublic;
};

export type WebhooksGetWebhookResponse = WebhooksGetWebhookResponses[keyof WebhooksGetWebhookResponses];

export type WebhooksUpdateWebhookData = {
    body: WebhookConfigUpdate;
    path: {
        /**
         * Webhook Id
         */
        webhook_id: string;
    };
    query?: never;
    url: '/api/v1/webhooks/{webhook_id}';
};

export type WebhooksUpdateWebhookErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type WebhooksUpdateWebhookError = WebhooksUpdateWebhookErrors[keyof WebhooksUpdateWebhookErrors];

export type WebhooksUpdateWebhookResponses = {
    /**
     * Successful Response
     */
    200: WebhookConfigPublic;
};

export type WebhooksUpdateWebhookResponse = WebhooksUpdateWebhookResponses[keyof WebhooksUpdateWebhookResponses];

export type ApiKeysListApiKeysData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/api-keys';
};

export type ApiKeysListApiKeysErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiKeysListApiKeysError = ApiKeysListApiKeysErrors[keyof ApiKeysListApiKeysErrors];

export type ApiKeysListApiKeysResponses = {
    /**
     * Successful Response
     */
    200: ApiKeysPublic;
};

export type ApiKeysListApiKeysResponse = ApiKeysListApiKeysResponses[keyof ApiKeysListApiKeysResponses];

export type ApiKeysCreateApiKeyData = {
    body: ApiKeyCreate;
    path?: never;
    query?: never;
    url: '/api/v1/api-keys';
};

export type ApiKeysCreateApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiKeysCreateApiKeyError = ApiKeysCreateApiKeyErrors[keyof ApiKeysCreateApiKeyErrors];

export type ApiKeysCreateApiKeyResponses = {
    /**
     * Successful Response
     */
    201: ApiKeyCreatePublic;
};

export type ApiKeysCreateApiKeyResponse = ApiKeysCreateApiKeyResponses[keyof ApiKeysCreateApiKeyResponses];

export type ApiKeysRevokeApiKeyData = {
    body?: never;
    path: {
        /**
         * Api Key Id
         */
        api_key_id: string;
    };
    query?: never;
    url: '/api/v1/api-keys/{api_key_id}/revoke';
};

export type ApiKeysRevokeApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiKeysRevokeApiKeyError = ApiKeysRevokeApiKeyErrors[keyof ApiKeysRevokeApiKeyErrors];

export type ApiKeysRevokeApiKeyResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ApiKeysRevokeApiKeyResponse = ApiKeysRevokeApiKeyResponses[keyof ApiKeysRevokeApiKeyResponses];

export type ApiKeysDeleteApiKeyData = {
    body?: never;
    path: {
        /**
         * Api Key Id
         */
        api_key_id: string;
    };
    query?: never;
    url: '/api/v1/api-keys/{api_key_id}';
};

export type ApiKeysDeleteApiKeyErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ApiKeysDeleteApiKeyError = ApiKeysDeleteApiKeyErrors[keyof ApiKeysDeleteApiKeyErrors];

export type ApiKeysDeleteApiKeyResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ApiKeysDeleteApiKeyResponse = ApiKeysDeleteApiKeyResponses[keyof ApiKeysDeleteApiKeyResponses];

export type InternalProcessNotificationData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/internal/notifications/send';
};

export type InternalProcessNotificationResponses = {
    /**
     * Response Internal-Process Notification
     *
     * Successful Response
     */
    200: {
        [key: string]: string;
    };
};

export type InternalProcessNotificationResponse = InternalProcessNotificationResponses[keyof InternalProcessNotificationResponses];

export type PrivateCreateUserData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserError = PrivateCreateUserErrors[keyof PrivateCreateUserErrors];

export type PrivateCreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserResponse = PrivateCreateUserResponses[keyof PrivateCreateUserResponses];
