// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type FCMTokenUpdate = {
    fcm_token: string;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PlanUpgrade = {
    plan_id: string;
};

export type PlanUpgradePublic = {
    message: string;
    data: {
        [key: string]: (string);
    };
};

export type SMSDeviceCreate = {
    name: string;
    phone_number: string;
    status?: string;
};

export type SMSDeviceCreatePublic = {
    device_id: string;
    api_key: string;
    status: string;
};

export type SMSDevicePublic = {
    name: string;
    phone_number: string;
    status?: string;
    id: string;
    user_id: string;
    last_heartbeat: (string | null);
    created_at: string;
    updated_at: string;
};

export type SMSDevicesPublic = {
    data: Array<SMSDevicePublic>;
    count: number;
};

export type SMSDeviceUpdate = {
    name?: (string | null);
    phone_number?: (string | null);
    status?: (string | null);
    fcm_token?: (string | null);
};

export type SMSIncoming = {
    from_number: string;
    body: string;
    timestamp?: (string | null);
};

export type SMSMessageCreate = {
    recipients: Array<(string)>;
    body: string;
    device_id?: (string | null);
};

export type SMSMessagePublic = {
    to: string;
    from_number?: (string | null);
    body: string;
    status?: string;
    message_type?: string;
    id: string;
    device_id: (string | null);
    user_id: string;
    webhook_sent: boolean;
    error_message: (string | null);
    created_at: string;
    updated_at: string;
    sent_at: (string | null);
    delivered_at: (string | null);
};

export type SMSMessageSendPublic = {
    message_ids: Array<(string)>;
    status: string;
};

export type SMSMessagesPublic = {
    data: Array<SMSMessagePublic>;
    count: number;
};

export type SMSReport = {
    message_id: string;
    status: string;
    error_message?: (string | null);
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPlanPublic = {
    name: string;
    max_sms_per_month?: number;
    max_devices?: number;
    price?: number;
    id: string;
    created_at: string;
    updated_at: string;
};

export type UserPlansPublic = {
    data: Array<UserPlanPublic>;
    count: number;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
};

export type UserQuotaPublic = {
    plan: string;
    sms_sent_this_month: number;
    max_sms_per_month: number;
    devices_registered: number;
    max_devices: number;
    reset_date: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type WebhookConfigCreate = {
    url: string;
    secret_key?: (string | null);
    events?: string;
    active?: boolean;
};

export type WebhookConfigPublic = {
    url: string;
    secret_key?: (string | null);
    events?: string;
    active?: boolean;
    id: string;
    user_id: string;
    created_at: string;
    updated_at: string;
};

export type WebhookConfigsPublic = {
    data: Array<WebhookConfigPublic>;
    count: number;
};

export type WebhookConfigUpdate = {
    url?: (string | null);
    secret_key?: (string | null);
    events?: (string | null);
    active?: (boolean | null);
};

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PlansListPlansResponse = (UserPlansPublic);

export type PlansGetQuotaResponse = (UserQuotaPublic);

export type PlansUpgradePlanData = {
    requestBody: PlanUpgrade;
};

export type PlansUpgradePlanResponse = (PlanUpgradePublic);

export type SmsSendSmsData = {
    requestBody: SMSMessageCreate;
};

export type SmsSendSmsResponse = (SMSMessageSendPublic);

export type SmsListMessagesData = {
    limit?: number;
    messageType?: (string | null);
    skip?: number;
};

export type SmsListMessagesResponse = (SMSMessagesPublic);

export type SmsGetMessageData = {
    messageId: string;
};

export type SmsGetMessageResponse = (SMSMessagePublic);

export type SmsListIncomingMessagesData = {
    limit?: number;
    skip?: number;
};

export type SmsListIncomingMessagesResponse = (SMSMessagesPublic);

export type SmsReportIncomingSmsData = {
    requestBody: SMSIncoming;
};

export type SmsReportIncomingSmsResponse = (Message);

export type SmsCreateDeviceData = {
    requestBody: SMSDeviceCreate;
};

export type SmsCreateDeviceResponse = (SMSDeviceCreatePublic);

export type SmsListDevicesData = {
    limit?: number;
    skip?: number;
};

export type SmsListDevicesResponse = (SMSDevicesPublic);

export type SmsGetDeviceData = {
    deviceId: string;
};

export type SmsGetDeviceResponse = (SMSDevicePublic);

export type SmsUpdateDeviceData = {
    deviceId: string;
    requestBody: SMSDeviceUpdate;
};

export type SmsUpdateDeviceResponse = (SMSDevicePublic);

export type SmsDeleteDeviceData = {
    deviceId: string;
};

export type SmsDeleteDeviceResponse = (Message);

export type SmsReportSmsStatusData = {
    requestBody: SMSReport;
};

export type SmsReportSmsStatusResponse = (Message);

export type SmsUpdateFcmTokenData = {
    requestBody: FCMTokenUpdate;
};

export type SmsUpdateFcmTokenResponse = (Message);

export type SmsDeviceHeartbeatResponse = (Message);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

export type WebhooksCreateWebhookData = {
    requestBody: WebhookConfigCreate;
};

export type WebhooksCreateWebhookResponse = (WebhookConfigPublic);

export type WebhooksListWebhooksData = {
    limit?: number;
    skip?: number;
};

export type WebhooksListWebhooksResponse = (WebhookConfigsPublic);

export type WebhooksGetWebhookData = {
    webhookId: string;
};

export type WebhooksGetWebhookResponse = (WebhookConfigPublic);

export type WebhooksUpdateWebhookData = {
    requestBody: WebhookConfigUpdate;
    webhookId: string;
};

export type WebhooksUpdateWebhookResponse = (WebhookConfigPublic);

export type WebhooksDeleteWebhookData = {
    webhookId: string;
};

export type WebhooksDeleteWebhookResponse = (Message);