"""Add SMSOutbox table

Revision ID: db80539b8422
Revises: 38a2c006503e
Create Date: 2025-12-31 14:17:14.727365

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'db80539b8422'
down_revision = '38a2c006503e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('smsoutbox',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sms_message_id', sa.Uuid(), nullable=False),
    sa.Column('device_id', sa.Uuid(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('sending_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['smsdevice.id'], ),
    sa.ForeignKeyConstraint(['sms_message_id'], ['smsmessage.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_smsoutbox_sms_message_id'), 'smsoutbox', ['sms_message_id'], unique=False)
    op.create_index(op.f('ix_smsoutbox_status'), 'smsoutbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_smsoutbox_status'), table_name='smsoutbox')
    op.drop_index(op.f('ix_smsoutbox_sms_message_id'), table_name='smsoutbox')
    op.drop_table('smsoutbox')
    # ### end Alembic commands ###
