/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CheckEmailRouteImport } from './routes/check-email'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as SubscriptionSuccessRouteImport } from './routes/subscription.success'
import { Route as SubscriptionErrorRouteImport } from './routes/subscription.error'
import { Route as OauthCallbackProviderRouteImport } from './routes/oauth-callback.$provider'
import { Route as LayoutWebhooksRouteImport } from './routes/_layout/webhooks'
import { Route as LayoutSmsRouteImport } from './routes/_layout/sms'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutIntegrationsRouteImport } from './routes/_layout/integrations'
import { Route as LayoutDevicesRouteImport } from './routes/_layout/devices'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckEmailRoute = CheckEmailRouteImport.update({
  id: '/check-email',
  path: '/check-email',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const SubscriptionSuccessRoute = SubscriptionSuccessRouteImport.update({
  id: '/subscription/success',
  path: '/subscription/success',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionErrorRoute = SubscriptionErrorRouteImport.update({
  id: '/subscription/error',
  path: '/subscription/error',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackProviderRoute = OauthCallbackProviderRouteImport.update({
  id: '/oauth-callback/$provider',
  path: '/oauth-callback/$provider',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutWebhooksRoute = LayoutWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSmsRoute = LayoutSmsRouteImport.update({
  id: '/sms',
  path: '/sms',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutIntegrationsRoute = LayoutIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutDevicesRoute = LayoutDevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/devices': typeof LayoutDevicesRoute
  '/integrations': typeof LayoutIntegrationsRoute
  '/settings': typeof LayoutSettingsRoute
  '/sms': typeof LayoutSmsRoute
  '/webhooks': typeof LayoutWebhooksRoute
  '/oauth-callback/$provider': typeof OauthCallbackProviderRoute
  '/subscription/error': typeof SubscriptionErrorRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin': typeof LayoutAdminRoute
  '/devices': typeof LayoutDevicesRoute
  '/integrations': typeof LayoutIntegrationsRoute
  '/settings': typeof LayoutSettingsRoute
  '/sms': typeof LayoutSmsRoute
  '/webhooks': typeof LayoutWebhooksRoute
  '/oauth-callback/$provider': typeof OauthCallbackProviderRoute
  '/subscription/error': typeof SubscriptionErrorRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/check-email': typeof CheckEmailRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/devices': typeof LayoutDevicesRoute
  '/_layout/integrations': typeof LayoutIntegrationsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/sms': typeof LayoutSmsRoute
  '/_layout/webhooks': typeof LayoutWebhooksRoute
  '/oauth-callback/$provider': typeof OauthCallbackProviderRoute
  '/subscription/error': typeof SubscriptionErrorRoute
  '/subscription/success': typeof SubscriptionSuccessRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/check-email'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/sms'
    | '/webhooks'
    | '/oauth-callback/$provider'
    | '/subscription/error'
    | '/subscription/success'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/check-email'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/admin'
    | '/devices'
    | '/integrations'
    | '/settings'
    | '/sms'
    | '/webhooks'
    | '/oauth-callback/$provider'
    | '/subscription/error'
    | '/subscription/success'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/check-email'
    | '/login'
    | '/privacy'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/_layout/admin'
    | '/_layout/devices'
    | '/_layout/integrations'
    | '/_layout/settings'
    | '/_layout/sms'
    | '/_layout/webhooks'
    | '/oauth-callback/$provider'
    | '/subscription/error'
    | '/subscription/success'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  CheckEmailRoute: typeof CheckEmailRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  OauthCallbackProviderRoute: typeof OauthCallbackProviderRoute
  SubscriptionErrorRoute: typeof SubscriptionErrorRoute
  SubscriptionSuccessRoute: typeof SubscriptionSuccessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-email': {
      id: '/check-email'
      path: '/check-email'
      fullPath: '/check-email'
      preLoaderRoute: typeof CheckEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/subscription/success': {
      id: '/subscription/success'
      path: '/subscription/success'
      fullPath: '/subscription/success'
      preLoaderRoute: typeof SubscriptionSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscription/error': {
      id: '/subscription/error'
      path: '/subscription/error'
      fullPath: '/subscription/error'
      preLoaderRoute: typeof SubscriptionErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-callback/$provider': {
      id: '/oauth-callback/$provider'
      path: '/oauth-callback/$provider'
      fullPath: '/oauth-callback/$provider'
      preLoaderRoute: typeof OauthCallbackProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/webhooks': {
      id: '/_layout/webhooks'
      path: '/webhooks'
      fullPath: '/webhooks'
      preLoaderRoute: typeof LayoutWebhooksRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/sms': {
      id: '/_layout/sms'
      path: '/sms'
      fullPath: '/sms'
      preLoaderRoute: typeof LayoutSmsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/integrations': {
      id: '/_layout/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof LayoutIntegrationsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/devices': {
      id: '/_layout/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof LayoutDevicesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutDevicesRoute: typeof LayoutDevicesRoute
  LayoutIntegrationsRoute: typeof LayoutIntegrationsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutSmsRoute: typeof LayoutSmsRoute
  LayoutWebhooksRoute: typeof LayoutWebhooksRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutDevicesRoute: LayoutDevicesRoute,
  LayoutIntegrationsRoute: LayoutIntegrationsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutSmsRoute: LayoutSmsRoute,
  LayoutWebhooksRoute: LayoutWebhooksRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  CheckEmailRoute: CheckEmailRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  OauthCallbackProviderRoute: OauthCallbackProviderRoute,
  SubscriptionErrorRoute: SubscriptionErrorRoute,
  SubscriptionSuccessRoute: SubscriptionSuccessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
